### ISSUE TITLE
PHP container fails to start: can't download v4

### ISSUE THREAD

**Issue by treyturner** [chevereto/v4-docker#50]
I'm unable to get the demo running via Docker 20.10.18 on Ubuntu 20.04.

```
user@droplet:~/v4-docker$ make demo
[+] Running 8/8
 ⠿ Container local_chevereto-4.0-php-8.1-demo_http      Remov...                                                   0.0s
 ⠿ Container local_chevereto-4.0-php-8.1-demo_php       Remove...                                                  0.0s
 ⠿ Container local_chevereto-4.0-php-8.1-demo_database  R...                                                       0.5s
 ⠿ Volume local_chevereto-docker-demo_assets            Removed                                                    0.0s
 ⠿ Volume local_chevereto-docker-demo_chevereto         Removed                                                    1.1s
 ⠿ Volume local_chevereto-docker-demo_database          Removed                                                    1.1s
 ⠿ Volume local_chevereto-docker-demo_storage           Removed                                                    0.0s
 ⠿ Network local_chevereto-docker-demo_chevereto        Removed                                                    0.2s
[+] Running 7/8cense key:
 ⠿ Network local_chevereto-docker-demo_chevereto        Created                                                    0.1s
 ⠿ Volume "local_chevereto-docker-demo_chevereto"       Create...                                                  0.0s
 ⠿ Volume "local_chevereto-docker-demo_database"        Created                                                    0.0s
 ⠿ Volume "local_chevereto-docker-demo_storage"         Created                                                    0.0s
 ⠿ Volume "local_chevereto-docker-demo_assets"          Created                                                    0.0s
 ⠿ Container local_chevereto-4.0-php-8.1-demo_database  H...                                                      28.3s
 ⠿ Container local_chevereto-4.0-php-8.1-demo_php       Waitin...                                                 37.2s
 ⠿ Container local_chevereto-4.0-php-8.1-demo_http      Creat...                                                   0.1s
container for service "php" is unhealthy
make: *** [Makefile:196: demo] Error 1
```

When I view the PHP container logs, I see:

```
user@droplet:~/v4-docker$ docker logs local_chevereto-4.0-php-8.1-demo_php
Restarting Mail Transport Agent (MTA): sendmail.
/var/CONTAINER_STARTED_PLACEHOLDER
Making working dir /chevereto/download
cd /chevereto/download
* Downloading chevereto/v4 4.0-lite package
> https://chevereto.com/api/download/4.0-lite
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 400 Bad Request
```

It seems the download URL [throws 400](https://chevereto.com/api/download/4.0-lite) because it's expecting a license key.

**Comment by rodber** [comment]
> It seems the download URL [throws 400](https://chevereto.com/api/download/4.0-lite) because it's expecting a license key.

Yes, it needs a key.

<img width="708" alt="CleanShot 2022-10-03 at 11 07 38@2x" src="https://user-images.githubusercontent.com/20590102/193598192-29dadba3-e358-43d6-af20-03afa53d7e31.png">

**Comment by treyturner** [comment]
I... don't even know where you took that screenshot from. Where do we get a demo license key?

It doesn't mention requiring a key for the demo in the v4-docker quickstart or it's documentation, but that repo is linked from somewhere in your docs that said you can 'get a demo anywhere with Docker'. Is this not the case

**Comment by treyturner** [comment]
Ok, I found it on the third page of docs, but the link sends me to a purchase page. Isn't the point of a demo that I can try it before buying it?

**Comment by rodber** [comment]
> I... don't even know where you took that screenshot from (...) It doesn't mention requiring a key for the demo in the v4-docker quickstart or it's documentation

From [the docs](https://github.com/chevereto/v4-docker/blob/4.0/docs/MAKE.md#demo) in this repo. I will add a "requires license key" at quick-start to avoid future confusion.

> Where do we get a demo license key? (...) said you can 'get a demo anywhere with Docker'. Is this not the case

We don't provide demo keys at this time. This repo is intended for development purposes and when using `make dev` you don't need a key (but you need a source project). I believe that the claim isn't misleading as you can run the demo anywhere with Docker... Is just that it requires a key for building the project with the source files.

If you aren't a customer then you can try the [online demo](https://demo.chevereto.com/).

> Isn't the point of a demo that I can try it self-hosted before buying it?

For the online demo yes, it is the point. But for this project the point of the demo is to provide a replicable context for testing for bugs in the software with [pre-made content](https://github.com/chevereto/demo-importing).

Sorry for the confusion.
